package com.angelsingh.weatherful.model

class WeatherModel {
    var iconMap: HashMap<Int,String> = hashMapOf(
            200 to "wi_day_thunderstorm",
            201 to "wi_thunderstorm",
            202 to "wi_thunderstorm",
            210 to "wi_day_thunderstorm",
            211 to "wi_thunderstorm",
            212 to "wi_thunderstorm",
            221 to "wi_thunderstorm",
            230 to "wi_storm_shower",
            231 to "wi_storm_showers",
            232 to "wi_thunderstorm",

            300 to "wi_day_sprinkle",
            301 to "wi_day_sprinkle",
            302 to "wi_sprinkle",
            310 to "wi_rain_mix",
            311 to "wi_sprinkle",
            312 to "wi_raindrops",
            313 to "wi_rain",
            314 to "wi_rain",
            321 to "wi_sprinkle",

            500 to "wi_day_rain",
            501 to "wi_rain",
            502 to "wi_rain",
            503 to "wi_rain",
            504 to "wi_rain",
            511 to "wi_rain_wind",
            520 to "wi_showers",
            521 to "wi_rain_mix",
            522 to "wi_rain",
            531 to "wi_storm_showers",

            600 to "wi_day_snow",
            601 to "wi_snow",
            602 to "wi_sleet",
            611 to "wi_snow",
            612 to "wi_snow",
            613 to "wi_snow",
            615 to "wi_rain_mix",
            616 to "wi_rain_mix",
            620 to "wi_rain_mix",
            621 to "wi_snow",
            622 to "wi_snow",

            701 to "wi_day_fog",
            711 to "wi_smoke",
            721 to "wi_day_haze",
            731 to "wi_dust",
            741 to "wi_fog",
            761 to "wi_dust",
            762 to "wi_dust",
            771 to "wi_cloudy_gusts",
            781 to "wi_tornado",

            800 to "wi_day_sunny",
            801 to "wi_cloudy_gusts",
            802 to "wi_cloudy_gusts",
            803 to "wi_cloudy_gusts",
            804 to "wi_cloudy",

            900 to "wi_tornado",
            901 to "wi_storm_showers",
            902 to "wi_hurricane",
            903 to "wi_snowflake_cold",
            904 to "wi_hot",
            905 to "wi_day_windy",
            906 to "wi_hail",
            957 to "wi_strong_wind",
    )
}

